### ISSUE TITLE
Vane in unknown horizontal position

### ISSUE THREAD

**Issue by tjwallace** [Sammy1Am/temp-issues#12]
I have 3 MSZ-GL06NA wall units which do not have controllable horizontal vanes.

I have disabled the select option like this:

```yaml
mitsubishi_uart:
  heatpump_uart: uart_hp
  selects:
    horizontal_vane_position_select:
      id: horizontal_vane_position_select
      disabled_by_default: true
```

But in the logs I see this when the unit is on:

```
[14:25:49][W][mitsubishi_uart:167]: Vane in unknown horizontal position 7
```

And when the unit is off or idle:

```
[14:40:10][W][mitsubishi_uart:167]: Vane in unknown horizontal position 0
```

I think I can just ignore the log message but could an option be added [here](https://github.com/Sammy1Am/mitsubishi-uart/blob/main/components/mitsubishi_uart/muart_packet.h#L251-L259) for `0x07` and `0x00`?
